import { prisma } from "./db";

/** Rassemble toutes les données de HubPlan dans un objet prêt à sérialiser. */
export async function exportAll() {
  const [
    users,
    projects,
    memberships,
    categories,
    boards,
    milestones,
    designElements,
    tags,
    workItems,
    dependencies,
    workItemTags,
    comments,
    timeSessions,
    wikiPages,
    media,
    proposals,
    proposalTasks,
    proposalDelegations,
    proposalVotes,
    tickets,
    ticketMessages,
  ] = await Promise.all([
    prisma.user.findMany(),
    prisma.project.findMany(),
    prisma.membership.findMany(),
    prisma.category.findMany(),
    prisma.board.findMany(),
    prisma.milestone.findMany(),
    prisma.designElement.findMany(),
    prisma.tag.findMany(),
    prisma.workItem.findMany(),
    prisma.dependency.findMany(),
    prisma.workItemTag.findMany(),
    prisma.comment.findMany(),
    prisma.timeSession.findMany(),
    prisma.wikiPage.findMany(),
    prisma.media.findMany(),
    prisma.proposal.findMany(),
    prisma.proposalTask.findMany(),
    prisma.proposalDelegation.findMany(),
    prisma.proposalVote.findMany(),
    prisma.ticket.findMany(),
    prisma.ticketMessage.findMany(),
  ]);

  return {
    app: "HubPlan",
    version: 1,
    exportedAt: new Date().toISOString(),
    users,
    projects,
    memberships,
    categories,
    boards,
    milestones,
    designElements,
    tags,
    workItems,
    dependencies,
    workItemTags,
    comments,
    timeSessions,
    wikiPages,
    media,
    proposals,
    proposalTasks,
    proposalDelegations,
    proposalVotes,
    tickets,
    ticketMessages,
  };
}
